version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies
  pre_build:
    commands:
      - echo "Entering app directory..."
      - cd Brain-Tasks-App  
      - pwd
      - ls -la
      - echo "Now inside Brain-Tasks-App"t
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_URI .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $IMAGE_URI
      - printf '[{"name":"%s","imageUri":"%s"}]' "$REPO_NAME" "$IMAGE_URI" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
