apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-svc
  labels:
    app: brain-tasks
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: brain-tasks
